// product constants

export const PRODUCT_LOADING = "PRODUCT_LOADING";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const CLEANUP_PRODUCT = "CLEANUP_PRODUCT";

//cart constants

export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";

export const LOAD_CART_FAILURE = "LOAD_CART_FAILURE";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CART_SAVE_ADDRESS = "CART_SAVE_ADDRESS";

export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_SET_PAYMENT_METHOD = "CART_SET_PAYMENT_METHOD";

//order constants

export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";

export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

//user constants

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

export const USER_LOADED = "USER_LOADED";

export const AUTH_FAILURE = "AUTH_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOG_OUT = "LOG_OUT";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const GET_PROFILE_ERROR = "PROFILE_ERROR";

export const LOAD_USER_FAILED = "LOAD_USER_FAILED";

//edit user
export const EDIT_USERNAME_SUCCESS = "EDIT_USERNAME_SUCCESS";

export const EDIT_USERNAME_FAILURE = "EDIT_USERNAME_FAILURE";

export const EDIT_PASSWORD_SUCCESS = "EDIT_PASSWORD_SUCCESS";

export const EDIT_PASSWORD_FAILURE = "EDIT_PASSWORD_FAILURE";

export const SET_ALERT = "SET_ALERT";

export const REMOVE_ALERT = "REMOVE_ALERT";
