export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
